name: terraform-docs

on:
  push:
    branches:
      - main
    paths:
      - "modules/**/*.tf"
      - "cli/terraform/**/*.tf"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform-docs for AWS module
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: modules/aws
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: github-actions
          git-push-user-email: github-actions@github.com

      - name: Render terraform-docs for GCP module
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: modules/gcp
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: github-actions
          git-push-user-email: github-actions@github.com

      - name: Render terraform-docs for Azure module
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: modules/azure
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-push-user-name: github-actions
          git-push-user-email: github-actions@github.com
